import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import getPlayerStats from "./apiCalls";
import axios from "axios";
import asyncExample from "./apiCalls";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
	const [points, setPoints] = useState();
	const [assists, setAssists] = useState();
	const [rebounds, setRebounds] = useState();

	useEffect(() => {
		axios
			.get(
				"https://www.balldontlie.io/api/v1/season_averages?season=2021&player_ids[]=115"
			)
			.then((res) => {
				const playerPoints = res.data.data[0].pts;
				const playerAssists = res.data.data[0].ast;
				const playerRebounds = res.data.data[0].reb;

				setPoints(playerPoints);
				setAssists(playerAssists);
				setRebounds(playerRebounds);
			});
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>NBA leaders</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>2021 Season Averages</h1>

				<div className={styles.grid}>
					<a href="https://nextjs.org/docs" className={styles.card}>
						<h2>Steph Curry &rarr;</h2>
						<img src="/steph.jpeg"></img>
						<p>Points - {points}</p>
						<p>Rebounds - {rebounds}</p>
						<p>Assists - {assists}</p>
					</a>
				</div>
			</main>

			<footer className={styles.footer}>
				<div>
					<a
						href="https://www.balldontlie.io/#introduction"
						target="_blank"
						rel="noopener noreferrer"
					>
						Powered by{" "}
						<span className={styles.logo}>
							<Image
								src="/cryingjordan.jpeg"
								alt="ballDontLie"
								width={35}
								height={35}
							/>
						</span>
					</a>
				</div>
			</footer>
		</div>
	);
};

export default Home;
