import type { NextPage, NextPageContext } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { PropsWithChildren, useEffect, useState } from "react";
import { any, number } from "prop-types";
import { Props } from "next/script";

const Header = () => {
	return (
		<>
			<Head>
				<title>NBA leaders</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className={styles.title}>2021 Season Averages</h1>
		</>
	);
};

export default Header;
